### ISSUE TITLE
Umgebungen

### ISSUE THREAD

**Issue by Annex31** [puenka/LinAlg1JerominSkript#29]
Hallo,

mein Name ist Harald und ich würde mich gerne bei eurem tollen Projekt beteiligen.

Was haltet ihr davon wenn wir Umgebungen benutzen? Wichtige Dinge gehören einfach hervorgehoben! (Dimensionssatz, Rangformel,...)

Mein Vorschlag wären mindestens 3 Umgebungen:
```latex
\newenvironment{lemma}[1]
  {\paragraph{#1}}
  {}
\newenvironment{satz}[1]
  {\paragraph{#1}}
  {}
\newenvironment{def}[1]
  {\paragraph{#1}}
  {}
```
---------------------------------------------------------------------------------------------------------------------------------------
Beispiel für die Verwendung:
```latex
\begin{satz}{Homomorphiesatz für lineare Abbildungen:}
	Für $ f\in \hom(V,W) $ ist $ f(V)\cong V/\ker f $ vermöge
		\[ V/\ker f\ni v+\ker f \overset{\phi}{\mapsto} f(v)\in f(V) \]
\end{satz}
```
vorher war es so:
```latex
\paragraph{Homomorphiesatz für lineare Abbildungen:}
	Für $ f\in \hom(V,W) $ ist $ f(V)\cong V/\ker f $ vermöge
		\[ V/\ker f\ni v+\ker f \overset{\phi}{\mapsto} f(v)\in f(V) \]
```
---------------------------------------------------------------------------------------------------------------------------------------
Also vom Schreibaufwand sollte es sich in Grenzen halten.

Dann hat man nämlich später mal die Chance einfach die Formatierung ändern zu können

Je nach Lust und Laune kann man da einfach die Formatierung wählen ob für Druck oder Bildschirmausgabe. So wie es jetzt ist kann man nämlich schwer zwischen wichtigen Dingen und dem Rest unterscheiden.

Ich habe mal ein Beispielsstyling erstellt, damit ihr seht was man später damit machen könnte
Was haltet ihr davon?

![umgebungen_bsp](https://cloud.githubusercontent.com/assets/15906840/11252781/42a2e942-8e38-11e5-9050-1ffbce1169bf.png)

Lg Harald

**Comment by puenka** [comment]
Hi Harald,

freut mich total, dass du dich beteiligen möchtest!
Ich habe mir auch schon einmal überlegt, die einzelnen Sätze und die dazugehörigen Beweise besser zu strukturieren, um auch bei einem schnellen Blick die betreffenden Stellen finden zu können, bzw. eben um die Sätze hervorzuheben.

Die von dir vorgeschlagene Lösung in einer Box finde ich prinzipiell gut, allerdings finde ich, dass das Farbschema so ziemlich nach Beamer aussieht (bzw. allgemein Bildschirmoptimiert), was ich in einem Schriftdokument eher nicht verwenden würde (aber das ist ja ohnehin vorerst nebensächlich).

Ich denke allerdings nicht, dass wir immer komplette Abschnitte in derartige Boxen setzen können, immerhin werden in der VO teilweise verschiedene Dinge (Def. und Satz) in einem Abschnitt erklärt.

Als Alternative schlage ich vor, das grundsätzliche Strukturierungsschema beizubehalten, mit derartigen Umgebungen dann die "vorhebungswürdigen" Formeln etc. zu dekorieren (gerne auch mit einer Wiederholung der Überschrift bzw. einer Beschreibung des Inhalts)

Was hältst du von dem Vorschlag bzw. meinen Bedenken?

Ich bitte auch um die Meinung von den anderen Beitragenden!

**Comment by Annex31** [comment]
Wie gesagt, über die Optik können wir später diskutieren, man kann ja das dann beliebig editieren! Denn Code den ich im ersten Post geschrieben habe bewirkt ja, dass sich an der Optik vorläufig nichts ändert.  Wichtig wäre jetzt mal die Dinge richtig zu strukturieren! Um später einfach darauf zugreifen zu können.

Deinen Bedenken verstehe ich daher nicht ganz. Was meinst du mit Abschnitte?  ich würde ja nur das in Umgebungen aufnehmen was auch wirklich dazugehört:
Z.B. so:
![umgebungen_bsp2](https://cloud.githubusercontent.com/assets/15906840/11253442/d85bcba4-8e3b-11e5-9184-99722a076444.png)

Meinst du dass diese Umklammerung manchmal nicht trivial ist, wie z.B. bei "Bsp & Definiton"? 
Dann würde ich halt nur die Dinge umklammern die eindeutig sind und alles andere so lassen wir bisher

**Comment by puenka** [comment]
Genau da sehe ich das Problem. Optisch wirkt es nämlich jetzt so, als würde die Definition zum Abschnitt "Übrigens" gehören, obwohl eigentlich ein neuer Abschnitt beginnt.

**Comment by Annex31** [comment]
Ja du hast recht meine Lösung aus dem ersten Post ist Blödsinn! Sorry.

Ich stimme deiner Variante 2 zu. Habe den Paragraph Befehl falsch verstanden!
Hatte nicht gecheckt dass du darauf hinaus willst! Sorry!

D.h. prinzipiell  findest du meinen Vorschlag ok?
Wie würdest du jetzt die  
\newenvironment{lemma}[1]
  {}
  {}
```Latex
Umgebungen definieren? 
Und vor allem welche (Satz, Definition, Lemma, Korollar, Beweis, Bsp, Bemerkung,..) ??

**Comment by puenka** [comment]
Ich hätte Satz,Def,Lemma,Korollar extra hervorgehoben, Beweis,Bsp,Bemerkung nicht, weil diese ja untergeordnet sind.

Ich verwende (aber erst seit Kurzem) \subparagraph für die Beweise,Bsp und Bemerkungen, um eben genau diese Unterteilung auch angedeutet zu haben.

Der erste Schritt ist, denke ich, die Umgebungen leer zu definieren und grundsätzlich unter \paragraph beginnen zu lassen, und rückwirkend die entsprechenden Bereiche zu fassen.

D.h. im "größten" Fall steht denn z.B.:
```LaTeX
\paragraph{Lemma}
\begin[optionaler Extratitel]{Lemma}
...
\end{Lemma}
\paragraph{Beweis}
```

**Comment by Annex31** [comment]
super, das hört sich gut an!

**Comment by puenka** [comment]
Leere Definitionen sind im master.tex eingefügt, die rückwirkende Einarbeitung ist noch ausständig...
