### ISSUE TITLE
Umstrukturierung mit subsections

### ISSUE THREAD

**Issue by puenka** [puenka/LinAlg1JerominSkript#34]
Ich schlage vor, die Struktur der Inhalte (ab momentan paragraph) um eine Ebene zu heben. subsection wird derzeit noch nicht verwendet, also schlage ich vor:

paragraph -> subsection
subparagraph -> paragraph

So hätten wir mehr Struktur durch mehr Kapitelnummerierungen im Skript.

**Comment by Annex31** [comment]
nur zur Info überhalb von paragraph kommt subsubsection

**Comment by puenka** [comment]
Ich weiß, aber ich denke die Formatierung ohne den Zeilenumbruch nach [Bemerkung, Beispiel, Beweis] ist sparsamer.
Bei subsubsection wird (soweit ich weiß) die ÜS in eine eigene Zeile gesetzt.
