### ISSUE TITLE
Formatierungsänderungen

### ISSUE THREAD

**Issue by tugit** [puenka/LinAlg1JerominSkript#42]
Da momentan vorlesungsfrei ist und sich einige Leute das Skriptum ausdrucken werden, sind Formatierungsänderungen momentan äußerst ungünstig, da dadurch alles neu gedruckt werden muss und wir außerdem momentan keine Möglichkeit haben, zu markieren was geändert wurde. Daher sollten wir ab jetzt eine extra PDF hochladen um die Formatierungsänderungen die ich gepusht habe  (sind zwar jetzt nicht viele, aber durch die Änderungen der Envs, wirkt es sich global aus) / ab jetzt gepusht werden zugänglich zu machen.
Oder sollten wir besser eine neue Branch erstellen für solche Änderungen und in der master branch nur gravierende Fehler beheben?

**Comment by puenka** [comment]
Ich schlage vor, diese Rücksichtname mit einem Release abzutun und dann einfach weiter zu verbessern - die Änderungen sind dann durch einen Vergleich mit der aktuellesten Version offensichtlich.
